from item import WeaponStandard, WeaponLarge, WeaponSmall, WeaponLong

ITEM_BASES = {
    'Driftwood Club': WeaponSmall,
    'Tribal Club': WeaponSmall,
    'Spiked Club': WeaponStandard,
    'Stone Hammer': WeaponStandard,
    'War Hammer': WeaponStandard,
    'Bladed Mace': WeaponStandard,
    'Ceremonial Mace': WeaponStandard,
    'Dream Mace': WeaponStandard,
    'Wyrm Mace': WeaponStandard,
    'Petrified Club': WeaponStandard,
    'Barbed Club': WeaponStandard,
    'Rock Breaker': WeaponStandard,
    'Battle Hammer': WeaponStandard,
    'Flanged Mace': WeaponStandard,
    'Ornate Mace': WeaponStandard,
    'Phantom Mace': WeaponStandard,
    'Dragon Mace': WeaponStandard,
    'Ancestral Club': WeaponStandard,
    'Tenderizer': WeaponStandard,
    'Gavel': WeaponStandard,
    'Legion Hammer': WeaponStandard,
    'Pernarch': WeaponStandard,
    'Auric Mace': WeaponStandard,
    'Nightmare Mace': WeaponStandard,
    'Behemoth Mace': WeaponStandard,

    'Driftwood Sceptre': WeaponSmall,
    'Darkwood Sceptre': WeaponStandard,
    'Bronze Sceptre': WeaponStandard,
    'Quartz Sceptre': WeaponStandard,
    'Iron Sceptre': WeaponStandard,
    'Ochre Sceptre': WeaponStandard,
    'Ritual Sceptre': WeaponStandard,
    'Shadow Sceptre': WeaponStandard,
    'Grinning Fetish': WeaponStandard,
    'Horned Sceptre': WeaponStandard,
    'Sekhem': WeaponStandard,
    'Crystal Sceptre': WeaponStandard,
    'Lead Sceptre': WeaponStandard,
    'Blood Sceptre': WeaponStandard,
    'Royal Sceptre': WeaponStandard,
    'Abyssal Sceptre': WeaponStandard,
    'Stag Sceptre': WeaponStandard,
    'Karui Sceptre': WeaponStandard,
    "Tyrant's Sekhem": WeaponStandard,
    'Opal Sceptre': WeaponStandard,
    'Platinum Sceptre': WeaponStandard,
    'Vaal Sceptre': WeaponStandard,
    'Carnal Sceptre': WeaponStandard,
    'Void Sceptre': WeaponStandard,
    'Sambar Sceptre': WeaponStandard,

    'Driftwood Maul': WeaponLarge,
    'Tribal Maul': WeaponLarge,
    'Mallet': WeaponLarge,
    'Sledgehammer': WeaponLarge,
    'Jagged Maul': WeaponLarge,
    'Brass Maul': WeaponLarge,
    'Fright Maul': WeaponLarge,
    'Morning Star': WeaponLarge,
    'Totemic Maul': WeaponLarge,
    'Great Mallet': WeaponLarge,
    'Steelhead': WeaponLarge,
    'Spiny Maul': WeaponLarge,
    'Plated Maul': WeaponLarge,
    'Dread Maul': WeaponLarge,
    'Solar Maul': WeaponLarge,
    'Karui Maul': WeaponLarge,
    'Colossus Mallet': WeaponLarge,
    'Piledriver': WeaponLarge,
    'Meatgrinder': WeaponLarge,
    'Imperial Maul': WeaponLarge,
    'Terror Maul': WeaponLarge,
    'Coronal Maul': WeaponLarge,

    'Rusted Sword': WeaponSmall,
    'Copper Sword': WeaponSmall,
    'Sabre': WeaponSmall,
    'Broad Sword': WeaponStandard,
    'War Sword': WeaponStandard,
    'Ancient Sword': WeaponStandard,
    'Elegant Sword': WeaponStandard,
    'Dusk Blade': WeaponStandard,
    'Hook Sword': WeaponStandard,
    'Variscite Blade': WeaponStandard,
    'Cutlass': WeaponStandard,
    'Baselard': WeaponStandard,
    'Battle Sword': WeaponStandard,
    'Elder Sword': WeaponStandard,
    'Graceful Sword': WeaponStandard,
    'Twilight Blade': WeaponStandard,
    'Grappler': WeaponStandard,
    'Gemstone Sword': WeaponStandard,
    'Corsair Sword': WeaponStandard,
    'Gladius': WeaponStandard,
    'Legion Sword': WeaponStandard,
    'Vaal Blade': WeaponStandard,
    'Eternal Sword': WeaponStandard,
    'Midnight Blade': WeaponStandard,
    'Tiger Hook': WeaponStandard,

    'Rusted Spike': WeaponLong,
    'Whalebone Rapier': WeaponLong,
    'Battered Foil': WeaponLong,
    'Basket Rapier': WeaponLong,
    'Jagged Foil': WeaponLong,
    'Antique Rapier': WeaponLong,
    'Elegant Foil': WeaponLong,
    'Thorn Rapier': WeaponLong,
    'Smallsword': WeaponLong,
    'Wyrmbone Rapier': WeaponLong,
    'Burnished Foil': WeaponLong,
    'Estoc': WeaponLong,
    'Serrated Foil': WeaponLong,
    'Primeval Rapier': WeaponLong,
    'Fancy Foil': WeaponLong,
    'Apex Rapier': WeaponLong,
    'Courtesan Sword': WeaponLong,
    'Dragonbone Rapier': WeaponLong,
    'Tempered Foil': WeaponLong,
    'Pecoraro': WeaponLong,
    'Spiraled Foil': WeaponLong,
    'Vaal Rapier': WeaponLong,
    'Jewelled Foil': WeaponLong,
    'Harpy Rapier': WeaponLong,
    'Dragoon Sword': WeaponLong,

    'Corroded Blade': WeaponLong,
    'Longsword': WeaponLong,
    'Bastard Sword': WeaponLarge,
    'Two-Handed Sword': WeaponLarge,
    'Etched Greatsword': WeaponLarge,
    'Ornate Sword': WeaponLarge,
    'Spectral Sword': WeaponLarge,
    'Curved Blade': WeaponLarge,
    'Butcher Sword': WeaponLarge,
    'Footman Sword': WeaponLarge,
    'Highland Blade': WeaponLarge,
    'Engraved Greatsword': WeaponLarge,
    'Tiger Sword': WeaponLarge,
    'Wraith Sword': WeaponLarge,
    'Lithe Blade': WeaponLarge,
    "Headman's Sword": WeaponLarge,
    'Reaver Sword': WeaponLarge,
    'Ezomyte Blade': WeaponLarge,
    'Vaal Greatsword': WeaponLarge,
    'Lion Sword': WeaponLarge,
    'Infernal Sword': WeaponLarge,
    'Exquisite Blade': WeaponLarge,

}
